const locale = ({
    en: {
        id : "Id",
        pseudonym:  "Pseudonym",
        pseudonymTaken : "The pseudonym has already taken",
        pseudonymPlaceHolder: "Enter pseudonym",
        description: "Description",
        descriptionPlaceHolder: "Enter description",
        loadPhoto : "Load picture",
        add : "Add",
        save : "Save",
        edit : "Edit",
        delete : "Delete",
        see : "See",
        modificationMessage : "Saved",
        removeMessage: "Deleted",
        about : "About the author",
        books : "Books",
        deleteAuthorMessage : "Deletion is not possible because the author has books",
        authorPicSize : "Image size must be less than 2MB",
        authorsListEmpty : "Author list is empty",
    },
    ru: {
       id : "код автора",
       pseudonym:  "Псевдоним",
       pseudonymTaken : "Псевдоним уже занят",
       pseudonymPlaceHolder: "Введите псевдоним автора",
       description: "Описание",
       descriptionPlaceHolder: "Введите описание автора",
       loadPhoto : "Загрузите фото",
       add : "Добавить",
       save : "Сохранить",
       edit : "Редактировать",
       delete : "Удалить",
       see : "Посмотреть",
       modificationMessage : "Сохранено",
       removeMessage: "Удалено",
       about : "Об авторе",
       books : "Книги",
       deleteAuthorMessage : "Удаление невозможно, так как у автора есть книги",
       authorPicSize : "Размер картинки должен быть меньше 2мб",
       authorsListEmpty : "Список авторов пуст",
    }
});
export default {locale};