const locale = ({
    en: {
        add: "Add",
        id : "id",
        name: "Name",
        description : "Description",
        genreTitle : "Genres",
        authorTitle : "Authors",
        price: "Price",
        amountPages : "Amount pages",
        inStock : "In stock",
        action : "Action",
        see: "See",
        publishedYear : "Published year",
        authorAlreadyAdded : "Автор уже добавлен",
        msgAuthor : "Choose authors",
        msgGenre : "Choose genre",
        msgSaved : "Saved",
        chooseAuthor: "Choose authors",
        weight : "Weight",
        materialCover : "Material cover",
        picture : "Picture",
        genres : [
            "Art",
            "Autobiography",
            "Biography",
            "Business",
            "Cookbook",
            "Dictionary",
            "Encyclopedia",
            "Guide",
            "Health",
            "History",
            "Philosophy",
            "Science",
            "Religion",
            "Kids",
            "Classic",
            "Drama",
            "Fairytale",
            "Fantasy",
            "Horrors",
            "Mystery",
            "Poetry",
            "Romance",
            "Thrillers",
        ],
        find : "search",
        deleteBtn : "Delete",
        addBtn : "Add",
        saveBtn : "Save",
        addToCart : "Add to cart",
        removeFromCart : "Remove from cart",
        editBtn : "Edit",
        notInStock : "No in stock",
        yes : "Yes",
        no : "No",
        authorTaken : "The author has already added",
        ascending : "Ascending",
        descending : "Descending",
        onlyInStock : "Only in stock",
        from : "from",
        to : "to",
        bookPicSize : "Image size of picture must be less 2mb",
        placeOrderBtn : "Place an order",
        emptyCart : "There is no any books in cart",
        listEmpty : "There is no any books",
    },
    ru: {
        add: "Добавить",
        id : "Код книги",
        name: "Название книги",
        description : "Описание",
        genreTitle : "Жанры",
        authorTitle : "Авторы",
        price: "Цена",
        amountPages : "Количество страниц",
        inStock : "В наличии",
        action : "Действие",
        see: "Посмотреть",
        publishedYear : "Год публикации",
        authorAlreadyAdded : "Автор уже добавлен",
        msgAuthor : "Выберите автора",
        msgGenre : "Выберите жанр",
        msgSaved : "Сохранено",
        chooseAuthor: "Выбрать автора",
        weight : "Вес",
        materialCover : "Переплет",
        picture : "Фото",
        find : "Найти",
        listEmpty : "Список книг пуст",
        genres : [
            "Искусство",
            "Автобиография",
            "Биография",
            "Бизнес литература",
            "Кулинария",
            "Словари",
            "Энциклопедии",
            "Справочники",
            "Здоровье",
            "История",
            "Философия",
            "Наука",
            "Религия",
            "Детская литература",
            "Классическая литература",
            "Драма",
            "Сказки",
            "Фэнтези",
            "Ужасы",
            "Мистика",
            "Поэмы",
            "Романы",
            "Триллеры",
        ],
        deleteBtn : "Удалить",
        addBtn : "Добавить",
        saveBtn : "Сохранить",
        addToCart : "Добавить в корзину",
        removeFromCart : "Удалить из корзины",
        editBtn : "Редактировать",
        notInStock : "Нет в наличии",
        yes : "Да",
        no : "Нет",
        authorTaken : "Автор уже добавлен",
        ascending : "По возрастанию",
        descending : "По убыванию",
        onlyInStock : "Только в наличии",
        from : "От",
        to : "До",
        bookPicSize : "Размер картинки должен быть меньше 2мб",
        placeOrderBtn : "Оформить заказ",
        emptyCart : "Нет товаров в корзине"
    },
});
export default {locale};