const locale = ({
    en: {
        id: "Id",
        name : "Name",
        count : "Count",
        startDate : "Start date",
        endDate : 'End date',
        discountFactor : 'Discount factor',
        chooseBookMessage : "Choose book",
        alreadyTaken : "Already taken",
        warnDateMessage: "The end date of the discount must be greater than the start date",
        books : "Books",
        addBtn : "Add",
        deleteBtn : "Delete",
        saveBtn : "Save",
        seeBtn: "See",
        editBtn: "Edit",
        alreadyOnDiscountBook : "The book has already on the discount",
        codeBook: "Book code",
        discountCode : "Discount code",
        deleteMsg : "Deleted",
        chooseBookBtn : "Choose book"
    },
    ru: {
        id: "Код",
        name : "Название",
        count : "Количество книг",
        startDate : "Дата начала скидки",
        endDate : 'Дата окончания скидки',
        discountFactor : 'Коэффициент скидки',
        chooseBookMessage : "Выберите книгу",
        alreadyTaken : "Данная книга уже добавлена",
        warnDateMessage: "Дата окончания скидки должна быть больше ее начала",
        books : "Книги",
        addBtn : "Добавить",
        deleteBtn : "Удалить",
        saveBtn : "Сохранить",
        seeBtn: "Посмотреть",
        editBtn: "Редактировать",
        alreadyOnDiscountBook : "Уже на скидке",
        codeBook: "Код книги",
        discountCode : "Код скидки",
        deleteMsg : "Удалено",
        chooseBookBtn : "Выберите книги"
    }
});
export default {locale};